export const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';

export const ADD_SHOP = 'ADD_SHOP';
export const EDIT_SHOP = 'EDIT_SHOP';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_SERIAL_NUMBER = 'EDIT_SERIAL_NUMBER';

export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAILURE = 'GET_SHOP_FAILURE';